package org.kanomchan.projectname.modulename.bean;


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SysMUserMapRoleId generated by hbm2java
 */
@Embeddable
public class UserMapRoleId implements java.io.Serializable {

	private long idUser;
	private long idRole;

	public UserMapRoleId() {
	}

	public UserMapRoleId(long idUser, long idRole) {
		this.idUser = idUser;
		this.idRole = idRole;
	}

	@Column(name = "ID_USER", nullable = false)
	public long getIdUser() {
		return this.idUser;
	}

	public void setIdUser(long idUser) {
		this.idUser = idUser;
	}

	@Column(name = "ID_ROLE", nullable = false)
	public long getIdRole() {
		return this.idRole;
	}

	public void setIdRole(long idRole) {
		this.idRole = idRole;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserMapRoleId))
			return false;
		UserMapRoleId castOther = (UserMapRoleId) other;

		return (this.getIdUser() == castOther.getIdUser())
				&& (this.getIdRole() == castOther.getIdRole());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getIdUser();
		result = 37 * result + (int) this.getIdRole();
		return result;
	}


}
