package org.kanomchan.projectname.modulename.bean;


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SysMUserMapRole generated by hbm2java
 */
@Entity
@Table(name = "SYS_M_USER_MAP_ROLE")
public class UserMapRole implements java.io.Serializable,
		org.kanomchan.core.common.bean.EntityBean {

	private UserMapRoleId id;
	private String status;
	private Date createDate;
	private String createUser;
	private Date updateDate;
	private String updateUser;

	public UserMapRole() {
	}

	public UserMapRole(UserMapRoleId id) {
		this.id = id;
	}

	public UserMapRole(UserMapRoleId id, String status,
			Date createDate, String createUser, Date updateDate,
			String updateUser) {
		this.id = id;
		this.status = status;
		this.createDate = createDate;
		this.createUser = createUser;
		this.updateDate = updateDate;
		this.updateUser = updateUser;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idUser", column = @Column(name = "ID_USER", nullable = false)),
			@AttributeOverride(name = "idRole", column = @Column(name = "ID_ROLE", nullable = false)) })
	public UserMapRoleId getId() {
		return this.id;
	}

	public void setId(UserMapRoleId id) {
		this.id = id;
	}

	@Column(name = "STATUS", length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "CREATE_DATE", length = 0)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "CREATE_USER")
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Column(name = "UPDATE_DATE", length = 0)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "UPDATE_USER")
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

}
