package org.kanomchan.formula.bean;

// Generated Oct 10, 2014 3:15:49 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Symbol generated by hbm2java
 */
@Entity
@Table(name = "FUM_M_SYMBOL")
public class Symbol implements java.io.Serializable {

	private String symbol;
	private String symbolType;
	private Set<FormulaEffect> formulaEffects = new HashSet<FormulaEffect>(0);

	public Symbol() {
	}

	public Symbol(String symbol) {
		this.symbol = symbol;
	}

	public Symbol(String symbol, String symbolType, Set<FormulaEffect> formulaEffects) {
		this.symbol = symbol;
		this.symbolType = symbolType;
		this.formulaEffects = formulaEffects;
	}

	@Id
	@Column(name = "SYMBOL", unique = true, nullable = false, length = 20)
	public String getSymbol() {
		return this.symbol;
	}

	public void setSymbol(String symbol) {
		this.symbol = symbol;
	}

	@Column(name = "SYMBOL_TYPE", length = 20)
	public String getSymbolType() {
		return this.symbolType;
	}

	public void setSymbolType(String symbolType) {
		this.symbolType = symbolType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "symbol")
	public Set<FormulaEffect> getFormulaEffects() {
		return this.formulaEffects;
	}

	public void setFormulaEffects(Set<FormulaEffect> formulaEffects) {
		this.formulaEffects = formulaEffects;
	}

}
