package org.kanomchan.formula.bean;


// Generated Oct 7, 2014 3:22:51 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FormulaEffectId generated by hbm2java
 */
@Embeddable
public class FormulaEffectId implements java.io.Serializable {

	private Long idFormula;
	private Long idFormulaInput;
	private String symbol;

	public FormulaEffectId() {
	}

	public FormulaEffectId(Long idFormula, Long idFormulaInput, String symbol) {
		this.idFormula = idFormula;
		this.idFormulaInput = idFormulaInput;
		this.symbol = symbol;
	}

	@Column(name = "ID_FORMULA", nullable = false)
	public Long getIdFormula() {
		return this.idFormula;
	}

	public void setIdFormula(Long idFormula) {
		this.idFormula = idFormula;
	}

	@Column(name = "ID_FORMULA_INPUT", nullable = false)
	public Long getIdFormulaInput() {
		return this.idFormulaInput;
	}

	public void setIdFormulaInput(Long idFormulaInput) {
		this.idFormulaInput = idFormulaInput;
	}

	@Column(name = "SYMBOL", nullable = false, length = 20)
	public String getSymbol() {
		return this.symbol;
	}

	public void setSymbol(String symbol) {
		this.symbol = symbol;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FormulaEffectId))
			return false;
		FormulaEffectId castOther = (FormulaEffectId) other;

		return ((this.getIdFormula() == castOther.getIdFormula()) || (this.getIdFormula() != null && castOther.getIdFormula() != null && this.getIdFormula().equals(castOther.getIdFormula())))
				&& ((this.getIdFormulaInput() == castOther.getIdFormulaInput()) || (this.getIdFormulaInput() != null && castOther.getIdFormulaInput() != null && this.getIdFormulaInput().equals(
						castOther.getIdFormulaInput())))
				&& ((this.getSymbol() == castOther.getSymbol()) || (this.getSymbol() != null && castOther.getSymbol() != null && this.getSymbol().equals(castOther.getSymbol())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdFormula() == null ? 0 : this.getIdFormula().hashCode());
		result = 37 * result + (getIdFormulaInput() == null ? 0 : this.getIdFormulaInput().hashCode());
		result = 37 * result + (getSymbol() == null ? 0 : this.getSymbol().hashCode());
		return result;
	}

}
