package org.kanomchan.formula.bean;


// Generated Oct 7, 2014 3:22:51 PM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Symbol generated by hbm2java
 */
@Entity
@Table(name = "FUM_M_SYMBOL")
public class Symbol implements java.io.Serializable{

	private String symbol;
	private String symbolType;
	private List<FormulaEffect> formulaEffects = new ArrayList<FormulaEffect>(0);

	public Symbol() {
	}

	public Symbol(String symbol) {
		this.symbol = symbol;
	}

	public Symbol(String symbol, List<FormulaEffect> formulaEffects) {
		this.symbol = symbol;
		this.formulaEffects = formulaEffects;
	}

	@Id
	@Column(name = "SYMBOL", unique = true, nullable = false, length = 20)
	public String getSymbol() {
		return this.symbol;
	}

	public void setSymbol(String symbol) {
		this.symbol = symbol;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "symbol")
	public List<FormulaEffect> getFormulaEffects() {
		return this.formulaEffects;
	}

	public void setFormulaEffects(List<FormulaEffect> formulaEffects) {
		this.formulaEffects = formulaEffects;
	}
	@Column(name = "SYMBOL_TYPE")
	public String getSymbolType() {
		return symbolType;
	}

	public void setSymbolType(String symbolType) {
		this.symbolType = symbolType;
	}
	
	

}
